var chalk = require('chalk');

module.exports = function () {

    console.log(chalk.yellow('HERE COME DAT BOIIIIII!!!'));
    console.log(chalk.green('                                           ,╓╖╗╗╗╣╣▄╦,                          '));
    console.log(chalk.green('                                  ,╓╦╗╬╣╬▓▓▓▓▓▓▓▓▓▓█▓▓▌⌐                        '));
    console.log(chalk.green('                                ╣▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓█████▓▓µ                       '));
    console.log(chalk.green('                                ▀█████▓▓▓▓▓▓▓▓▓▓▓██████▓▓▄                      '));
    console.log(chalk.green('                                 ▀███████████▓▓▓▓█████████▓µ                    '));
    console.log(chalk.green('                                  ╙██████████████▓▓▓▓▓▓▓▓▓▓▓⌐                   '));
    console.log(chalk.green('                                    ▓████████████████▓▓▓▓▓▓▓▌                   '));
    console.log(chalk.green('                                     ╙█████████████████▓▓▓▓▓▓▒                  '));
    console.log(chalk.green('                                       ▐██████████████▓▓▓▓▓▓▓▓µ                 '));
    console.log(chalk.green('                                        ╫███████████▓▓▓▓▓▓▓▓▓▓▓⌐                '));
    console.log(chalk.green('                                        ╫███████████▓▓▓▓▓▓▓▓▓▓█▓⌐               '));
    console.log(chalk.green('                                       ▄████████████▓▓▓▓▓▓▓▓▓███▓               '));
    console.log(chalk.green('                                     ╓▓▓█████████████████▓▓▓▓▓███▓              '));
    console.log(chalk.green('                             ,,╗▄▓▓▓▓█▓███████████████████▓▓▓▓▓▓▓█▓⌐            '));
    console.log(chalk.green('                       ,╓╓╦╬▓▓▓▓█████████▀╠████████▓▓▓██████▓▓▓▓▓▓█▓            '));
    console.log(chalk.green('                  ╓╦╣▓▓▓▓▓▓▓▓▓▓███████▀`  ╫█████▓▓▓▓▓▓▓█▓▓████▓▓▓▓▓█▄,,╓▄       '));
    console.log(chalk.green('              ╥╬▓▓▓▓▓▓▓▓▓▓██████▓▀▀▀      ▓████▓▓▓▓▓▓▓▓█████▓▓█▓▓▓▓▓▓▓▓▀        '));
    console.log(chalk.green('          ,╗╣▓▓▓▓▓████████▀▀╙            ]█████▓▓▓▓▓▓▓▓█████▓▓▓▓▓▓▓██╨          '));
    console.log(chalk.green('  ╦▄▄▄▓▓▓▓▓▓███▀▀▀▀▀▀╙                   ║████▓▓▓▓▓▓▓███████▓▓▓▓▓███▓           '));
    console.log(chalk.green('  ╙╙▀▀████████▀                          ║███████▓▓▓████████▓▓▓█████▌           '));
    console.log(chalk.green('      ╙╙`╙▀▀                             .██████████████████████▓▓▓█Ö           '));
    console.log(chalk.green('                                          ╠█████████████████████▓▓▓▓▌⌐          '));
    console.log(chalk.green('                                         ,▓██████████████████████▓▓▓▓▓ç         '));
    console.log(chalk.green('                                        ╓▓███████████████████████▓▓▓▓▓▓▓╦       '));
    console.log(chalk.green('                                       ╬██████████████████████████▓▓▓▓▓▓▓µ      '));
    console.log(chalk.green('                                      ╫███████████████████████████▓▓▓▓▓▓█▓▄     '));
    console.log(chalk.green('                                     ▓████████████████████████████▓▓▓▓▓▓▓██µ    '));
    console.log(chalk.green('                                    ▓███████████████▀▀▀▓███████████▓▓▓▓▓▓▓█▌    '));
    console.log(chalk.green('                                   ╫█████████████▀▄▓███████████████▓▓▓▓▓▓▓▓█∩   '));
    console.log(chalk.green('                                 ▄▓██████████▀▐▄████████████████████▓▓▓▓▓▓▓█▄   '));
    console.log(chalk.green('                               ,▓███████▀▀    ╫██████▓██▓▓▀▀▀▀▀▀▀▀▓█▓▓▓▓▓███▌   '));
    console.log(chalk.green('                               ╣██████▒               ▓▓          "▓█▓▓▓▓███▀   '));
    console.log(chalk.green('                              ╓▓▓▓█████╕              ▓▓           `▓█▓▓▓███∩   '));
    console.log(chalk.green('                               ▓█▓▓▓████▄             ▓▌            └▓▓▓▓███    '));
    console.log(chalk.green('                                ▀██▓▓▓████Q          ▐▓▌            ╓▓▓▓▓██▌    '));
    console.log(chalk.green('                                 `▀▓███████▄         ╠╬▌           ║▓▓▓▓▓▓█∩    '));
    console.log(chalk.green('                                    ╙▀██▓███▓╕     ╓╬▓▌╬╬⌐        ╔▓▓▓▓▓▓▓█∩    '));
    console.log(chalk.green('                                       ╙▀▓████▌▄▄▄▄▓▓█▄╬╬▄,      ,▓▓▓▓▓▓███∩    '));
    console.log(chalk.green('                                          ▐▓███████████▒▓███▓▄,  ╬█▓▓▓▓▓██▌     '));
    console.log(chalk.green('                                        ╓▄█████████████▒▓███████▄▓▓▓▓▓▓███∩     '));
    console.log(chalk.green('                                      ╗▓█████████████▌╠╬▓█████████▓▓▓▓▓██▓      '));
    console.log(chalk.green('                                    ╓▓█████████▄▓██▓█▒╫╬▓▌█Ü▀████▓▓▓▓▓███∩      '));
    console.log(chalk.green('                                   ▄█████████████▓▓██Ö╠╬▓█▀  .▓██▓▓▓▓███▌       '));
    console.log(chalk.green('                                 .▓████▓█╨  ╙██▌ ╠▓█▓ ╠╬█▓   ╫▓▓█▓▓▓▓███∩       '));
    console.log(chalk.green('                                ╓▓███▓█▓▓,   ╙██µ╠▓▓█⌐▌╬█∩  ╬█▀▓▓▓▓▓████        '));
    console.log(chalk.green('                               ╓▓███▓██▄▒▀▄    ██╠╬▓▓⌐▌╫▌  ▄█╨╓█▓▓▓▓████▌       '));
    console.log(chalk.green('                               ▓███▓█▀ ╙▀▓▄▓▄   ▓▓╬╫█µ╬▌  ▄▌  ╠█▓▓▓██████∩      '));
    console.log(chalk.green('                              ║████▓▌     ╙▓█▓⌐ ²█▓▓█▄╬▓╦▓▌  ╓▓▓▓▓▓██████▌      '));
    console.log(chalk.green('                              ████▓█▀▄▄,     ▀█▄ ╠████╬▓█▌ ╓▓▓▓▓▓▓██▀█████      '));
    console.log(chalk.green('                             ╓████▓█▓▄▄▓▓▓▄▄   ╙█▓▓█▓█╬▓▓▄▓╨ ╓▓▓▓██▓▓█████      '));
    console.log(chalk.green('                             ╠███▓█▒    ╙╙▀▀▓▓▓▄▓▓████╬▓█▄▄▄▄▓▓▓▓█▓╝╝█████      '));
    console.log(chalk.green('                             ▓███▓█           ;▓▓████▌▒▒╬╬▌╙╠▓▓▓█▓   █████      '));
    console.log(chalk.green('                             ▓███▓█╦▄▄╣▀▓▓███▓▀▀▒▓█████▓▓▀▓▓▓▓▓▓█▒  ┌█████      '));
    console.log(chalk.green('                             ▓███▓█▄▄╣▀▀▀`.  ,▄▓▀▓█████▒▓▄µ╠▓▓▓██▓▀▀▓████▌      '));
    console.log(chalk.green('                             ▀███▓█▌      ,▄██▀╓▓█╢███▓▒▌ ▀█▓▓██╨╙▀▀█████▒      '));
    console.log(chalk.green('                             ]██████   ╓▄▓▓▓╨ ╓██Ü▓█▓██▒▓▌╠▓▓▓█▒   ▄████▓       '));
    console.log(chalk.green('                              ▓███▓█▌▓▀▀▓▓╨  ▄██∩╔█▌╫█▓╬▓█▓▓▓█▓▀▄ ╓█████∩       '));
    console.log(chalk.green('                              ╚██████▄▓▀   ,▓▓▓  ▓█▒]█▓╫▒█▓▓▓█∩ `▓█████▀        '));
    console.log(chalk.green('                               ▀████▓█╦   ╓▓▄▓  ╫▓▓ ]█▓╫Q╣▓▓█▀  ▄█████▀         '));
    console.log(chalk.green('                                ▓██████▄ ╬▓▄▓  ╓█▓▌ ]█▌╫▒▓▓▓█▄╓▓█████▌          '));
    console.log(chalk.green('                                 ▀███████▌▓▓   ▓▌▓∩  ▓▒╬▄▓█▓▓▓▓▓████▀           '));
    console.log(chalk.green('                                  ╙████████▄  ╓█╢▌   ▓▓███████████▀▀Θ           '));
    console.log(chalk.green('                                    ▀██████████▓▓▄,╓▄████████████╨              '));
    console.log(chalk.green('                                      ▀███████████████████████▀╨                '));
    console.log(chalk.green('                                        ╙▀█████████████████▀╙                   '));
    console.log(chalk.green('                                            ╙╙▀▀▓██▀▀▀▀▀                        '));

};